import { analyzeProject } from "@/lib/analyze";
import type { Project, ProjectTask, TaskStatus } from "@/lib/types";
import { proposalForChanges, simulateProposal } from "./proposals";
import type { AgentEvidence, AgentProposal, ProposalAction, ProposalChange, ProposalValue, TaskFilter, ToolExecution, ToolName } from "./types";

export type OpenAIToolDefinition = { type: "function"; name: ToolName; description: string; strict: true; parameters: Record<string, unknown> };
const emptySchema = { type: "object", properties: {}, required: [], additionalProperties: false };
const stringField = (description: string) => ({ type: "string", description });
const taskItemSchema = {
  type: "object",
  properties: { title: stringField("Task title"), owner: stringField("Exact name of an existing team member"), dueDate: stringField("YYYY-MM-DD"), estimatedHours: { type: "number", minimum: 0 }, critical: { type: "boolean" } },
  required: ["title", "owner", "dueDate", "estimatedHours", "critical"], additionalProperties: false
};

export const agentToolDefinitions: OpenAIToolDefinition[] = [
  { type: "function", name: "get_project_overview", description: "Read current identity, dates, progress, financials, status, and deterministic health score.", strict: true, parameters: emptySchema },
  { type: "function", name: "analyze_budget", description: "Calculate live budget consumption, projected final cost, remaining budget, and overrun risk.", strict: true, parameters: emptySchema },
  { type: "function", name: "analyze_schedule", description: "Calculate live planned versus actual progress, overdue tasks, date completeness, and deadline risk.", strict: true, parameters: emptySchema },
  { type: "function", name: "analyze_capacity", description: "Read live team allocations, overload, and only data-supported available capacity.", strict: true, parameters: emptySchema },
  { type: "function", name: "list_tasks", description: "List live tasks by filter and optional assignee.", strict: true, parameters: { type: "object", properties: { filter: { type: ["string", "null"], enum: ["all", "blocked", "overdue", "critical", "incomplete", "completed", "deferred", null] }, assignee: { type: ["string", "null"] } }, required: ["filter", "assignee"], additionalProperties: false } },
  { type: "function", name: "inspect_task", description: "Read one task by exact stable ID from list_tasks.", strict: true, parameters: { type: "object", properties: { taskId: stringField("Exact task ID") }, required: ["taskId"], additionalProperties: false } },
  { type: "function", name: "analyze_quality", description: "Inspect live quality score, blockers, overruns, and evidence sufficiency.", strict: true, parameters: emptySchema },
  { type: "function", name: "get_health_findings", description: "Read deterministic risks, severity, evidence, and recommendations calculated by the app.", strict: true, parameters: emptySchema },
  { type: "function", name: "request_clarification", description: "Ask one focused follow-up question with two to six concrete options when the goal or choice is ambiguous. Does not change project data.", strict: true, parameters: { type: "object", properties: { question: stringField("Focused question"), options: { type: "array", minItems: 2, maxItems: 6, items: { type: "object", properties: { id: stringField("Stable short option ID"), label: stringField("User-facing option") }, required: ["id", "label"], additionalProperties: false } }, allowMultiple: { type: "boolean" } }, required: ["question", "options", "allowMultiple"], additionalProperties: false } },
  { type: "function", name: "simulate_changes", description: "Simulate a proposal ID on a deep copy. Never mutates real project data.", strict: true, parameters: { type: "object", properties: { proposalId: stringField("Proposal ID returned by a proposal tool") }, required: ["proposalId"], additionalProperties: false } },
  { type: "function", name: "propose_task_update", description: "Create an approval-only proposal to update one existing task. Never applies it. A blocked status requires blocker detail.", strict: true, parameters: { type: "object", properties: { taskId: stringField("Exact task ID"), field: { type: "string", enum: ["status", "dueDate", "owner", "critical", "estimatedHours"] }, value: stringField("New value encoded as text; status may be not-started, in-progress, blocked, deferred, or done"), blocker: { type: ["string", "null"], description: "Required reason when status becomes blocked; otherwise null" }, reason: stringField("Evidence-based reason") }, required: ["taskId", "field", "value", "blocker", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_task_create", description: "Create an approval-only proposal for a follow-up task with explicit details. Owner must already be on the project team.", strict: true, parameters: { type: "object", properties: { ...taskItemSchema.properties, reason: stringField("Why this task is needed") }, required: [...taskItemSchema.required, "reason"], additionalProperties: false } },
  { type: "function", name: "propose_task_delete", description: "Create a prominent approval-only deletion proposal for one exact task. Never applies it.", strict: true, parameters: { type: "object", properties: { taskId: stringField("Exact task ID"), reason: stringField("Clear reason deletion is appropriate") }, required: ["taskId", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_allocation_change", description: "Create an approval-only allocation proposal for one existing team member.", strict: true, parameters: { type: "object", properties: { memberId: stringField("Exact member ID"), allocation: { type: "number", minimum: 0, maximum: 200 }, reason: stringField("Evidence-based reason") }, required: ["memberId", "allocation", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_allocation_rebalance", description: "Create one approval-only proposal that changes allocations for two existing team members.", strict: true, parameters: { type: "object", properties: { fromMemberId: stringField("Exact source member ID"), fromAllocation: { type: "number", minimum: 0, maximum: 200 }, toMemberId: stringField("Exact destination member ID"), toAllocation: { type: "number", minimum: 0, maximum: 200 }, reason: stringField("Evidence-based reason") }, required: ["fromMemberId", "fromAllocation", "toMemberId", "toAllocation", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_deadline_change", description: "Create an approval-only project deadline proposal using YYYY-MM-DD. A deadline move is a planning decision, not a guaranteed fix.", strict: true, parameters: { type: "object", properties: { deadline: stringField("New deadline in YYYY-MM-DD"), reason: stringField("Evidence-based reason") }, required: ["deadline", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_budget_change", description: "Create an approval-only non-negative approved-budget/reforecast proposal. Never claim this reduces actual cost.", strict: true, parameters: { type: "object", properties: { budget: { type: "number", minimum: 0 }, reason: stringField("Evidence-based reason") }, required: ["budget", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_project_update", description: "Create an approval-only correction to a safe project field.", strict: true, parameters: { type: "object", properties: { field: { type: "string", enum: ["name", "client", "owner", "startDate", "spent", "progress", "plannedProgress", "qualityScore"] }, value: stringField("New value encoded as text"), reason: stringField("Evidence-based reason") }, required: ["field", "value", "reason"], additionalProperties: false } },
  { type: "function", name: "propose_checklist", description: "Create an approval-only estimate-validation checklist as one to five explicit tasks.", strict: true, parameters: { type: "object", properties: { title: stringField("Checklist title"), reason: stringField("Why validation is required"), items: { type: "array", minItems: 1, maxItems: 5, items: taskItemSchema } }, required: ["title", "reason", "items"], additionalProperties: false } },
  { type: "function", name: "propose_recovery_plan", description: "Create an approval-only recovery plan with up to three concrete, separately displayed changes.", strict: true, parameters: { type: "object", properties: { title: stringField("Short plan title"), reason: stringField("Why these interventions are ranked highest"), changes: { type: "array", minItems: 1, maxItems: 3, items: { type: "object", properties: { actionType: { type: "string", enum: ["task_update", "allocation_change", "deadline_change", "budget_change", "project_update"] }, entityId: stringField("Exact task, member, or project ID"), field: stringField("Field to update"), value: stringField("New value encoded as text"), reason: stringField("Reason for this intervention"), expectedImpact: stringField("Expected non-guaranteed effect") }, required: ["actionType", "entityId", "field", "value", "reason", "expectedImpact"], additionalProperties: false } } }, required: ["title", "reason", "changes"], additionalProperties: false } }
];

const record = (value: unknown): Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {};
const requiredString = (args: Record<string, unknown>, key: string) => { const value = args[key]; if (typeof value !== "string" || !value.trim()) throw new Error(`${key} is required.`); return value.trim(); };
const requiredNumber = (args: Record<string, unknown>, key: string) => { const value = args[key]; if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${key} must be a number.`); return value; };
const requiredBoolean = (args: Record<string, unknown>, key: string) => { const value = args[key]; if (typeof value !== "boolean") throw new Error(`${key} must be true or false.`); return value; };
const currentDate = (iso: string) => { const parsed = new Date(iso); return Number.isNaN(parsed.getTime()) ? new Date() : parsed; };
const validDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T12:00:00Z`));
const dateTime = (value: string, end = false) => validDate(value) ? new Date(`${value}T${end ? "23:59:59" : "12:00:00"}Z`).getTime() : null;
const formatMoney = (value: number, project: Project) => new Intl.NumberFormat("en-GB", { style: "currency", currency: project.currency, maximumFractionDigits: 0 }).format(value);
const evidence = (label: string, value: string, source: string): AgentEvidence => ({ label, value, source });
const changeId = () => crypto.randomUUID();

function normalizeValue(action: ProposalAction, field: string, value: string): ProposalValue {
  if (action === "allocation_change" || action === "budget_change" || ["spent", "progress", "plannedProgress", "qualityScore", "estimatedHours"].includes(field)) {
    const numeric = Number(value); if (!Number.isFinite(numeric)) throw new Error(`${field} must be numeric.`); return numeric;
  }
  if (field === "critical") { if (!/^(true|false)$/i.test(value)) throw new Error("critical must be true or false."); return value.toLowerCase() === "true"; }
  return value;
}

function taskValue(task: ProjectTask, field: string): ProposalValue {
  if (field === "status") return task.status;
  if (field === "dueDate") return task.dueDate;
  if (field === "owner") return task.owner;
  if (field === "critical") return task.critical;
  if (field === "blocker") return task.blocker;
  if (field === "estimatedHours") return task.estimatedHours;
  throw new Error(`Unknown task field ${field}.`);
}

function proposalChange(project: Project, input: { actionType: ProposalAction; entityId: string; field: string; newValue: ProposalValue; reason: string; expectedImpact: string }, support: string[]): ProposalChange {
  if (input.actionType === "task_update") {
    const task = project.tasks.find((item) => item.id === input.entityId); if (!task) throw new Error(`Task ${input.entityId} was not found.`);
    return { id: changeId(), ...input, entityType: "task", entityName: task.title, oldValue: taskValue(task, input.field), evidence: support, reversible: true };
  }
  if (input.actionType === "allocation_change") {
    const member = project.team.find((item) => item.id === input.entityId); if (!member) throw new Error(`Team member ${input.entityId} was not found.`);
    return { id: changeId(), ...input, entityType: "team_member", entityName: member.name, oldValue: member.allocation, evidence: support, reversible: true };
  }
  if (input.entityId !== project.id) throw new Error("The proposal targets an unknown project.");
  const oldValue = project[input.field as keyof Project];
  if (typeof oldValue !== "string" && typeof oldValue !== "number" && typeof oldValue !== "boolean") throw new Error(`Project field ${input.field} is invalid.`);
  return { id: changeId(), ...input, entityType: "project", entityName: project.name, oldValue, evidence: support, reversible: true };
}

function taskFromArgs(args: Record<string, unknown>): ProjectTask {
  return { id: crypto.randomUUID(), title: requiredString(args, "title"), owner: requiredString(args, "owner"), status: "not-started", dueDate: requiredString(args, "dueDate"), estimatedHours: requiredNumber(args, "estimatedHours"), loggedHours: 0, critical: requiredBoolean(args, "critical"), blocker: "" };
}

function createTaskChange(task: ProjectTask, reason: string): ProposalChange {
  return { id: changeId(), actionType: "task_create", entityType: "task", entityId: task.id, entityName: task.title, field: "__create__", oldValue: null, newValue: task, reason, evidence: [`${task.owner} · due ${task.dueDate} · ${task.estimatedHours}h estimate`], expectedImpact: "Adds explicit follow-up work; no delivery improvement is assumed until it is completed.", reversible: true };
}

export function getTaskMatches(project: Project, query: string): ProjectTask[] { const needle = query.trim().toLowerCase(); return needle ? project.tasks.filter((task) => task.id.toLowerCase() === needle || task.title.toLowerCase().includes(needle)) : []; }
export function getMemberMatches(project: Project, query: string) { const needle = query.trim().toLowerCase(); return needle ? project.team.filter((member) => member.id.toLowerCase() === needle || member.name.toLowerCase() === needle || member.name.toLowerCase().includes(needle)) : []; }

export function executeAgentTool(name: ToolName, rawArgs: unknown, project: Project, nowIso: string, proposals: AgentProposal[] = []): ToolExecution {
  const args = record(rawArgs); const now = currentDate(nowIso); const analysis = analyzeProject(project, now);
  const none = (output: Record<string, unknown>, summary: string, items: AgentEvidence[] = []): ToolExecution => ({ output, summary, evidence: items, proposal: null });
  if (name === "get_project_overview") return none({ id: project.id, updatedAt: project.updatedAt, name: project.name, owner: project.owner || null, customer: project.client || null, startDate: project.startDate || null, deadline: project.deadline || null, progress: project.progress, budget: project.budget, spent: project.spent, status: analysis.status, healthScore: analysis.score, missingData: [!project.owner && "owner", !validDate(project.startDate) && "start date", !validDate(project.deadline) && "deadline"].filter(Boolean) }, `${project.name} is ${analysis.status} at ${analysis.score}/100`, [evidence("Health", `${analysis.score}/100 · ${analysis.status}`, "deterministic health analysis")]);
  if (name === "analyze_budget") {
    const projectedFinalCost = project.progress > 0 ? project.spent / (project.progress / 100) : null; const remainingBudget = project.budget - project.spent; const projectedOverrun = projectedFinalCost === null ? null : Math.max(0, projectedFinalCost - project.budget); const consumption = project.budget > 0 ? (project.spent / project.budget) * 100 : null;
    return none({ budget: project.budget, spent: project.spent, progress: project.progress, consumptionPercent: consumption === null ? null : Math.round(consumption), projectedFinalCost: projectedFinalCost === null ? null : Math.round(projectedFinalCost), remainingBudget, projectedOverrun: projectedOverrun === null ? null : Math.round(projectedOverrun), evidenceSufficient: project.progress > 0 && project.budget > 0 }, projectedFinalCost === null ? "A final-cost forecast needs actual progress above 0%." : `Projected final cost is ${formatMoney(projectedFinalCost, project)}`, [evidence("Budget", `${formatMoney(project.spent, project)} spent of ${formatMoney(project.budget, project)} at ${project.progress}% progress`, "project budget data")]);
  }
  if (name === "analyze_schedule") {
    const nowMs = now.getTime(); const overdue = project.tasks.filter((task) => !["done", "deferred"].includes(task.status) && dateTime(task.dueDate, true) !== null && (dateTime(task.dueDate, true) as number) < nowMs); const deadlineMs = dateTime(project.deadline, true); const daysRemaining = deadlineMs === null ? null : Math.ceil((deadlineMs - nowMs) / 86_400_000); const missingDates = project.tasks.filter((task) => !validDate(task.dueDate)).map((task) => ({ id: task.id, title: task.title }));
    return none({ plannedProgress: project.plannedProgress, actualProgress: project.progress, scheduleGap: analysis.metrics.scheduleGap, overdueTasks: overdue, daysRemaining, missingDates, evidenceSufficient: deadlineMs !== null }, `${Math.max(0, analysis.metrics.scheduleGap)}pp behind plan with ${overdue.length} overdue task${overdue.length === 1 ? "" : "s"}`, [evidence("Schedule", `${project.progress}% actual vs ${project.plannedProgress}% planned`, "project progress data"), evidence("Dates", deadlineMs === null ? "Project deadline is missing or invalid" : `${project.deadline} · ${daysRemaining} days remaining`, "project dates")]);
  }
  if (name === "analyze_capacity") { const overloaded = project.team.filter((member) => member.allocation > 100); const available = project.team.filter((member) => member.allocation < 100).map((member) => ({ id: member.id, name: member.name, role: member.role, allocation: member.allocation, availableCapacity: 100 - member.allocation })); return none({ allocations: project.team, overloaded, available, evidenceSufficient: project.team.length > 0 }, `${overloaded.length} overloaded team member${overloaded.length === 1 ? "" : "s"}`, project.team.map((member) => evidence(member.name, `${member.allocation}% allocation`, "team allocation data"))); }
  if (name === "list_tasks") {
    const filter = (typeof args.filter === "string" ? args.filter : "all") as TaskFilter; const assignee = typeof args.assignee === "string" ? args.assignee.toLowerCase() : ""; const nowMs = now.getTime();
    const tasks = project.tasks.filter((task) => { if (assignee && !task.owner.toLowerCase().includes(assignee)) return false; if (filter === "blocked") return task.status === "blocked"; if (filter === "overdue") return !["done", "deferred"].includes(task.status) && dateTime(task.dueDate, true) !== null && (dateTime(task.dueDate, true) as number) < nowMs; if (filter === "critical") return task.critical; if (filter === "incomplete") return !["done", "deferred"].includes(task.status); if (filter === "completed") return task.status === "done"; if (filter === "deferred") return task.status === "deferred"; return true; });
    return none({ filter, assignee: assignee || null, tasks }, `${tasks.length} matching task${tasks.length === 1 ? "" : "s"}`, tasks.slice(0, 6).map((task) => evidence(task.title, `${task.status} · due ${task.dueDate || "missing"} · ${task.owner || "unassigned"}`, "task data")));
  }
  if (name === "inspect_task") { const taskId = requiredString(args, "taskId"); const task = project.tasks.find((item) => item.id === taskId); if (!task) throw new Error(`Task ${taskId} was not found.`); return none({ task, ownerOnTeam: project.team.some((member) => member.name === task.owner), dueDateValid: validDate(task.dueDate), estimateValid: Number.isFinite(task.estimatedHours) && task.estimatedHours >= 0 }, `${task.title} is ${task.status}`, [evidence(task.title, `${task.status} · ${task.loggedHours}/${task.estimatedHours}h · due ${task.dueDate || "missing"}`, "task data"), ...(task.blocker ? [evidence("Blocker", task.blocker, "task blocker data")] : [])]); }
  if (name === "analyze_quality") { const unresolved = project.tasks.filter((task) => task.status === "blocked" || (task.loggedHours > task.estimatedHours && !["done", "deferred"].includes(task.status))); return none({ qualityScore: project.qualityScore, unresolvedIssues: unresolved, evidenceSufficient: Number.isFinite(project.qualityScore) }, `Quality is ${project.qualityScore}/100 with ${unresolved.length} unresolved delivery signal${unresolved.length === 1 ? "" : "s"}`, [evidence("Quality", `${project.qualityScore}/100`, "project quality data"), evidence("Unresolved", `${unresolved.length} blocked or overrun tasks`, "task data")]); }
  if (name === "get_health_findings") return none({ score: analysis.score, status: analysis.status, findings: analysis.risks }, `${analysis.risks.length} deterministic findings, led by ${analysis.risks[0]?.title ?? "no immediate risk"}`, analysis.risks.slice(0, 5).map((risk) => evidence(risk.title, `${risk.severity}: ${risk.summary}`, "deterministic health findings")));
  if (name === "request_clarification") {
    const question = requiredString(args, "question");
    if (!Array.isArray(args.options) || args.options.length < 2 || args.options.length > 6) throw new Error("Clarification requires two to six options.");
    const options = args.options.map((value) => { const item = record(value); return { id: requiredString(item, "id"), label: requiredString(item, "label") }; });
    const clarification = { id: crypto.randomUUID(), question, options, allowMultiple: requiredBoolean(args, "allowMultiple") };
    return { output: { clarification }, summary: `Clarification requested: ${question}`, evidence: [], proposal: null, clarification };
  }
  if (name === "simulate_changes") { const proposalId = requiredString(args, "proposalId"); const proposal = proposals.find((item) => item.id === proposalId); if (!proposal) throw new Error(`Proposal ${proposalId} is not available to simulate.`); const { simulation } = simulateProposal(project, proposal, now); return none({ proposalId, ...simulation }, simulation.afterScore === null ? simulation.caveat : `Forecast moves health from ${simulation.beforeScore} to ${simulation.afterScore} (${simulation.scoreDelta && simulation.scoreDelta > 0 ? "+" : ""}${simulation.scoreDelta ?? 0})`, [evidence("Simulation", simulation.afterScore === null ? simulation.caveat : `${simulation.beforeScore} → ${simulation.afterScore}; forecast, not guarantee`, "temporary project copy")]); }

  let proposal: AgentProposal;
  if (name === "propose_task_update") {
    const taskId = requiredString(args, "taskId"); const field = requiredString(args, "field"); const value = normalizeValue("task_update", field, requiredString(args, "value")); const reason = requiredString(args, "reason"); const task = project.tasks.find((item) => item.id === taskId); if (!task) throw new Error(`Task ${taskId} was not found.`);
    const taskEvidence = [`${task.title}: ${task.status}${task.blocker ? ` · ${task.blocker}` : ""}`]; if (field === "dueDate" && typeof value === "string" && validDate(project.deadline) && value > project.deadline) taskEvidence.push(`Conflict: proposed task date ${value} is after project deadline ${project.deadline}`);
    const changes = [proposalChange(project, { actionType: "task_update", entityId: taskId, field, newValue: value, reason, expectedImpact: field === "status" && value === "deferred" ? "Removes the task from active delivery scope; this is a scope decision, not completed work." : "Updates the recorded task and reruns health analysis." }, taskEvidence)];
    if (field === "status" && value === "blocked") { const blocker = typeof args.blocker === "string" ? args.blocker.trim() : ""; if (!blocker) throw new Error("A blocker reason is required before marking a task blocked."); changes.push(proposalChange(project, { actionType: "task_update", entityId: taskId, field: "blocker", newValue: blocker, reason, expectedImpact: "Records the evidence behind the blocked status." }, [blocker])); }
    if (field === "status" && value !== "blocked" && task.status === "blocked" && task.blocker) changes.push(proposalChange(project, { actionType: "task_update", entityId: taskId, field: "blocker", newValue: "", reason, expectedImpact: "Clears the resolved blocker detail." }, [task.blocker]));
    proposal = proposalForChanges(project, `Update ${task.title}`, reason, changes, now);
  } else if (name === "propose_task_create") {
    const task = taskFromArgs(args); const reason = requiredString(args, "reason"); proposal = proposalForChanges(project, `Create follow-up task: ${task.title}`, reason, [createTaskChange(task, reason)], now);
  } else if (name === "propose_task_delete") {
    const taskId = requiredString(args, "taskId"); const reason = requiredString(args, "reason"); const task = project.tasks.find((item) => item.id === taskId); if (!task) throw new Error(`Task ${taskId} was not found.`); const change: ProposalChange = { id: changeId(), actionType: "task_delete", entityType: "task", entityId: task.id, entityName: task.title, field: "__delete__", oldValue: task, newValue: null, reason, evidence: [`${task.status} · ${task.owner || "unassigned"} · due ${task.dueDate || "missing"}`], expectedImpact: "Permanently removes the task from active project data; use defer when work may return.", reversible: true }; proposal = proposalForChanges(project, `Delete task: ${task.title}`, reason, [change], now);
  } else if (name === "propose_allocation_change") {
    const memberId = requiredString(args, "memberId"); const allocation = requiredNumber(args, "allocation"); const reason = requiredString(args, "reason"); const member = project.team.find((item) => item.id === memberId); if (!member) throw new Error(`Team member ${memberId} was not found.`); proposal = proposalForChanges(project, `Adjust ${member.name}'s allocation`, reason, [proposalChange(project, { actionType: "allocation_change", entityId: memberId, field: "allocation", newValue: allocation, reason, expectedImpact: allocation <= 100 ? "Removes this recorded overload if no other allocation exceeds 100%." : "Changes recorded capacity pressure." }, [`${member.name} is currently at ${member.allocation}%`])], now);
  } else if (name === "propose_allocation_rebalance") {
    const reason = requiredString(args, "reason"); const fromId = requiredString(args, "fromMemberId"); const toId = requiredString(args, "toMemberId"); if (fromId === toId) throw new Error("Rebalance requires two different people."); const changes = [proposalChange(project, { actionType: "allocation_change", entityId: fromId, field: "allocation", newValue: requiredNumber(args, "fromAllocation"), reason, expectedImpact: "Reduces or changes source workload." }, [reason]), proposalChange(project, { actionType: "allocation_change", entityId: toId, field: "allocation", newValue: requiredNumber(args, "toAllocation"), reason, expectedImpact: "Adds or changes destination workload using recorded capacity only." }, [reason])]; proposal = proposalForChanges(project, "Rebalance team allocation", reason, changes, now);
  } else if (name === "propose_deadline_change") {
    const deadline = requiredString(args, "deadline"); const reason = requiredString(args, "reason"); const conflicts = project.tasks.filter((task) => !["done", "deferred"].includes(task.status) && validDate(task.dueDate) && task.dueDate > deadline); proposal = proposalForChanges(project, "Change project deadline", reason, [proposalChange(project, { actionType: "deadline_change", entityId: project.id, field: "deadline", newValue: deadline, reason, expectedImpact: "Changes the planning window; it does not resolve underlying delivery work by itself." }, [`Current deadline is ${project.deadline || "missing"}`, ...(conflicts.length ? [`Conflict: ${conflicts.length} active task due date(s) fall after ${deadline}: ${conflicts.map((task) => task.title).join(", ")}`] : [])])], now);
  } else if (name === "propose_budget_change") {
    const budget = requiredNumber(args, "budget"); const reason = requiredString(args, "reason"); proposal = proposalForChanges(project, "Reforecast approved budget", reason, [proposalChange(project, { actionType: "budget_change", entityId: project.id, field: "budget", newValue: budget, reason, expectedImpact: "Aligns approved budget with the forecast; it does not reduce actual or projected cost." }, [`Current budget is ${formatMoney(project.budget, project)}`])], now);
  } else if (name === "propose_project_update") {
    const field = requiredString(args, "field"); const value = normalizeValue("project_update", field, requiredString(args, "value")); const reason = requiredString(args, "reason"); proposal = proposalForChanges(project, `Correct project ${field}`, reason, [proposalChange(project, { actionType: "project_update", entityId: project.id, field, newValue: value, reason, expectedImpact: "Corrects the selected input and triggers deterministic reassessment." }, [`Current ${field}: ${String(project[field as keyof Project])}`])], now);
  } else if (name === "propose_checklist") {
    const title = requiredString(args, "title"); const reason = requiredString(args, "reason"); if (!Array.isArray(args.items) || args.items.length === 0 || args.items.length > 5) throw new Error("Checklist requires one to five tasks."); const changes = args.items.map((item) => createTaskChange(taskFromArgs(record(item)), reason)); proposal = proposalForChanges(project, title, reason, changes, now, "checklist");
  } else {
    const title = requiredString(args, "title"); const reason = requiredString(args, "reason"); if (!Array.isArray(args.changes) || args.changes.length === 0 || args.changes.length > 3) throw new Error("Recovery plan requires one to three changes.");
    const changes = args.changes.map((raw) => { const item = record(raw); const actionType = requiredString(item, "actionType") as ProposalAction; const entityId = requiredString(item, "entityId"); const field = requiredString(item, "field"); const itemReason = requiredString(item, "reason"); return proposalChange(project, { actionType, entityId, field, newValue: normalizeValue(actionType, field, requiredString(item, "value")), reason: itemReason, expectedImpact: requiredString(item, "expectedImpact") }, [itemReason]); }); proposal = proposalForChanges(project, title, reason, changes, now, "recovery_plan");
  }
  return { output: { proposal }, summary: `Created approval proposal: ${proposal.title}`, evidence: proposal.changes.flatMap((change) => change.evidence.map((item) => evidence(change.entityName, item, "proposal evidence"))), proposal };
}

export function isToolName(value: string): value is ToolName { return agentToolDefinitions.some((tool) => tool.name === value); }
export function taskStatusFromText(value: string): TaskStatus | null { const normalized = value.toLowerCase().trim().replace(/\s+/g, "-"); if (["done", "completed", "complete"].includes(normalized)) return "done"; if (["in-progress", "started", "active", "unblocked"].includes(normalized)) return "in-progress"; if (["not-started", "unstarted", "todo", "to-do"].includes(normalized)) return "not-started"; if (normalized === "blocked") return "blocked"; if (["deferred", "defer", "postponed"].includes(normalized)) return "deferred"; return null; }
